### ISSUE TITLE
QA: Profile issue

### ISSUE THREAD

**Issue by Alexander4788** [iliran11/typing-game-2#10]
1. Facebook profile picture does not sync
2. The loading time of the this element is too long, reaches 7 seconds after the entire site has been uploaded
![profile](https://user-images.githubusercontent.com/46414084/51135580-1377bb00-1843-11e9-9e33-e764aa18bec4.png)

**Comment by iliran11** [comment]
לגבי שינוי התמונה של פייסבוק
בשביל להקל על הפיתוח אני משתמש בשירות של חברה שנקראת cloudinary
הם נותנים שירות בחינם וזה חסך לי עבודה

תראה מה הם כותבים, עבור חשבון חינם זה בודק אוטומטית כל 7 ימים:

Cloudinary automatically checks whether whether Facebook pictures have changed, according to a pre-defined caching period. If so, Cloudinary automatically re-fetches the original image as well as all transformed images. By default, Facebook images are checked for changes once every 7 days. Cloudinary customers with a paid account can request to change this default expiration time to any desired interval by submitting a support request.
