### ISSUE TITLE
empty state for profile page. (when user didnt play a single game)

### ISSUE THREAD

**Issue by iliran11** [iliran11/typing-game-2#16]
need to design this page.

![image](https://user-images.githubusercontent.com/24987188/51208190-a1bc7180-1915-11e9-993b-3802ba230e9a.png)

**Comment by Alexander4788** [comment]
ignore the background 
![first time](https://user-images.githubusercontent.com/46414084/51425566-673d2800-1be6-11e9-85a5-6c4e323bce08.png)
