### ISSUE TITLE
New Profile 

### ISSUE THREAD

**Issue by Alexander4788** [iliran11/typing-game-2#21]
כנכס ל-Profile_Multiplayer באפיון
https://ar3x63.axshare.com

הסבר:

**יוזר ותיק (כלומר עשה מבחן ושיחק גם מהמחשב וגם מהפלאפון):**

- כשהיוזר **נכנס מהפלאפון**, נתוני משחק\מבחן שביצע דרך הפלאפון מופיעים בהתחלה (ובגלילה הוא יכול לצפות בנתונים מהמשחקים שביצע דרך המחשב (1)

- כשהיוזר **נכנס דרך המחשב**, נתוני משחק\מבחן שביצע דרך המחשב מופיעים בהתחלה (ובגלילה הוא יכול לצפות בנתונים מהמשחקים שביצע דרך הפאלפון (2) -שים לב הסיטואציה הזאת תופיע רק בוואב (למרות שזה מאופיין בגדלים של מובייל)

**יוזר ותיק רק דרך המובייל**
- כשהיוזר שיחק רק דרך המובייל, ונכנס לפרופיל מהמובייל הוא יראה תוצאות שקשורות רק למובייל (3) 
- כשהיוזר שיחק רק דרך המובייל, ונכנס פתאום דרך המחשב לפרופיל יופיע בתחילת הפרופיל הודעה שהוא צריך לשחק, ולאחר מכן הנתוני משחק שלו מהמבחנים בפלאפון (4)

**יוזר ותיק רק דרך המחשב**
- כשהיוזר שיחק רק דרך המחשב, ונכנס פתאום לפרופיל דרך המובייל  (5)

**יוזר חדש**
- כשהיוזר נכנס בפעם הראשונה לפרופיל דרך המובייל (6)

-כשהיוזר נכנס בפעם הראשונה לפרופיל דרך המחשב (7)

לסיכום: 
תמיד יוצגו בעדיפות ראשונה הנתונים הקשורים למכשיר ממנו נכנס המשתמש (כלומר אם הוא נכנס מהמובייל יוצגו הנתונים שקשורים למובייל ראשונים)
במידה והמשתמש נכנס מהמובייל אבל שיחק קודם לכן רק במחשב, קודם כל תופיע לו הודעה שהוא צריך לשחק ורק לאחר מכן הנתונים שקשורים למחשב.
אם המשתמש נכנס לפרופיל מהמובייל (ואף פעם לא שיחק במחשב) יופיעו לו רק נתונים שקשורים למובייל, ואותו דבר גם מהצד של המשתמש במחשב.
ובמידה והמשתמש לא שיחק אף פעם לא מהמחשב ולא מהמובייל, תופיע לו הודעה שקשורה למכשיר שממנו נכנכס המשתמש (6) (7)

**Comment by iliran11** [comment]
implement in later time.
