### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Alexander4788** [iliran11/typing-game-2#26]
16x16
![Favicon16](https://user-images.githubusercontent.com/46414084/55570622-72dfbb80-570c-11e9-94c3-831c4a2c16ed.png)

32x32
![Favicon32](https://user-images.githubusercontent.com/46414084/55570623-72dfbb80-570c-11e9-94ce-fc19abc7055a.png)

57x57
![Favicon57](https://user-images.githubusercontent.com/46414084/55570625-73785200-570c-11e9-98f1-9119968ddfe3.png)

60x60
![Favicon60](https://user-images.githubusercontent.com/46414084/55570626-73785200-570c-11e9-98d3-a8aaecb96552.png)

64x64
![Favicon64](https://user-images.githubusercontent.com/46414084/55570627-73785200-570c-11e9-8480-2dcebdc8968b.png)

70x70
![Favicon70](https://user-images.githubusercontent.com/46414084/55570628-73785200-570c-11e9-8b40-894b6bf62063.png)

72x72
![Favicon72](https://user-images.githubusercontent.com/46414084/55570630-7410e880-570c-11e9-9147-4de013b427fe.png)

76x76
![Favicon76](https://user-images.githubusercontent.com/46414084/55570631-7410e880-570c-11e9-9b3e-9bc1c5b063ed.png)

96x96
![Favicon96](https://user-images.githubusercontent.com/46414084/55570632-7410e880-570c-11e9-900e-295daec4288e.png)

114x114
![Favicon114](https://user-images.githubusercontent.com/46414084/55570633-7410e880-570c-11e9-99ca-c16095b49077.png)

120x120
![Favicon120](https://user-images.githubusercontent.com/46414084/55570634-7410e880-570c-11e9-8d2e-8e13ef281e1e.png)

144x144
![Favicon144](https://user-images.githubusercontent.com/46414084/55570635-74a97f00-570c-11e9-8027-17908e4e17d3.png)

150x150
![Favicon150](https://user-images.githubusercontent.com/46414084/55570636-74a97f00-570c-11e9-9e81-e4a16fb1b669.png)

152x152
![Favicon152](https://user-images.githubusercontent.com/46414084/55570637-74a97f00-570c-11e9-8ace-1de61bd4ecc7.png)

160x160
![Favicon160](https://user-images.githubusercontent.com/46414084/55570638-74a97f00-570c-11e9-8a78-da606c804c00.png)

180x180
![Favicon180](https://user-images.githubusercontent.com/46414084/55570639-74a97f00-570c-11e9-9b0d-955e825d875f.png)

196x196
![Favicon196](https://user-images.githubusercontent.com/46414084/55570640-75421580-570c-11e9-8bd0-21826aed1810.png)

310x310
![Favicon310](https://user-images.githubusercontent.com/46414084/55570641-75421580-570c-11e9-999a-423eb0943b3f.png)

@iliran11

**Comment by iliran11** [comment]
not acceptable icons
